### ISSUE TITLE
Decrease wasm transferred size, to target <300kb.

### ISSUE THREAD

**Issue by wiedld** [influxdata/flux-lsp#432]
Note this is transferred size, not original size.

See details/numbers here:
https://github.com/influxdata/ui/issues/4226#issuecomment-1081265334

**Comment by onelson** [comment]
I think we discussed this previously, but [`wasm-strip`](https://webassembly.github.io/wabt/doc/wasm-strip.1.html) might get us some low hanging fruit on the overall size.

I'm not sure what to expect if we attempted to use standard js minification tooling on wasm since I mostly assumed the wasm portion would be less human-readble anyway.

**Comment by rockstar** [comment]
`wasm-strip` got us about 120 bytes by removing the producers header, but the other things that `wasm-strip` would provide to us are already being stripped out with `wasm-opt -Oz`. I think, for the most part, the low hanging fruit is gone, but there may be some slightly higher fruit that can be stripped. I see some functions that I know aren't being used but still exported, and I'm currently experimenting with `wasm-snip` to more code paths removed.

**Comment by onelson** [comment]
Well that's a bummer... :rofl:

**Comment by rockstar** [comment]
Here's a list of things that I learned in the process of working on #433 that don't have easy/addressable answers.

- First and foremost, the call graph of twiggy is complex and deep enough that to go deeper, we'd have to probably create some tools to parse twiggy output as json and find a better representation of that data. It's _very_ hard to spelunk through it: it's very comprehensive, and there's _a lot_ of data there.
- Semantic analysis apis bring in a whopping ~1MB (uncompressed) to the wasm binary, due to bringing in the stdlib and the files associated with it. That's not ideal, but here's where it becomes a hard problem: you could create an api to load that dynamically, but now you're trying to distribute the same amount of data across multiple http connections–that's often more expensive than one big file.
- The tower apis account for about 800k (uncompressed), and there's not a clear way of reducing that. I didn't see any default features that we could drop, and we're not really do anything funky where we're bringing in code that wouldn't otherwise be part of this. It's not entirely clear that, without just going back to pre `0.6` strategy of handling our own I/O. Even then, I'm not sure that we'd get any substantial gains there.
- The parser and formatter code accounts for about 700k (uncompressed). That code is all pretty straight-forward, so I don't think there is much to gain there.
- There are (potentially) some slight gains in size to be made, but at the expense of performance. I'm not sure the wasm is _super_ performance sensitive, but it wasn't clear that the size was significant to make those decisions. Before we go any farther there, we probably want to get serious about instrumenting experiments.

At this point, I'm fairly confident (though disappointed) to report that I think the wasm binary is about as small as it's ever going to be. It'll probably inflate by a slight amount as we add an API for walking an AST, but I don't expect it to get much bigger than it is now.
